
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: led-apagado-chorus-menu
*
* preset name: Color A8R8G8B8
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Custom, not_used not_used
* split to rows: yes
* bits per pixel: 32
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t ledapagadochorusmenu[36] = {
    // ░∙░
    // ∙∙∙
    // ░∙░
    0x5c, 0x4a, 0x26, 0x85, 0x1f, 0x1b, 0x27, 0xf3, 0x72, 0x5b, 0x1b, 0x85, 
    0x04, 0x08, 0x4f, 0xf9, 0x00, 0x00, 0x7a, 0xff, 0x16, 0x15, 0x2d, 0xf3, 
    0x48, 0x38, 0x44, 0x85, 0x12, 0x0d, 0x4b, 0xf4, 0x62, 0x4d, 0x2f, 0x85
};


