
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: led-prendido-chorus-menu
*
* preset name: Color A8R8G8B8
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Custom, not_used not_used
* split to rows: yes
* bits per pixel: 32
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t ledprendidochorusmenu[36] = {
    // ▒▒▒
    // ░░▒
    // ▒▒▒
    0x7b, 0x63, 0x9b, 0x85, 0x36, 0x2f, 0xf6, 0xf3, 0x98, 0x79, 0x95, 0x85, 
    0x07, 0x0e, 0xfc, 0xf9, 0x00, 0x00, 0xff, 0xff, 0x27, 0x24, 0xf6, 0xf3, 
    0x60, 0x4b, 0xad, 0x85, 0x20, 0x17, 0xf9, 0xf4, 0x83, 0x67, 0xa1, 0x85
};

